Repository tgyuuAn/SWM-ServerDriven-AOS, pull requests merged in 2024-07, with the labels that each got.

#2 feature/#1
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  build.gradle.kts
  data/src/androidTest/java/com/swm/data/ExampleInstrumentedTest.kt
  data/src/main/AndroidManifest.xml
  data/src/main/java/com/swm/data/network/di/DataModule.kt
  data/src/main/java/com/swm/data/network/di/NetworkModule.kt
  data/src/main/java/com/swm/data/network/dto/ScreenDTO.kt
  data/src/main/java/com/swm/data/network/repository/ScreenRepositoryImpl.kt
  data/src/main/java/com/swm/data/network/source/ScreenDataSource.kt
  data/src/main/java/com/swm/data/network/util/await.kt
  data/src/test/java/com/swm/data/ExampleUnitTest.kt
  data/src/test/java/com/swm/data/GsonTest.kt
  domain/build.gradle.kts
  domain/src/main/java/com/swm/domain/MyClass.kt
  domain/src/main/java/com/swm/domain/model/Screen.kt
  domain/src/main/java/com/swm/domain/repository/ScreenRepository.kt
  domain/src/main/java/com/swm/domain/usecase/GetScreenUseCase.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/androidTest/java/com/swm/presentation/ExampleInstrumentedTest.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/swm/presentation/MainActivity.kt
  presentation/src/main/java/com/swm/presentation/MainViewModel.kt
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/test/java/com/swm/presentation/ExampleUnitTest.kt
Labels: feature

#6 Feature/#5
  data/src/main/java/com/swm/data/network/di/NetworkModule.kt
  data/src/main/java/com/swm/data/network/dto/ScreenDTO.kt
  data/src/main/java/com/swm/data/network/dto/ViewTypeDto.kt
  data/src/test/java/com/swm/data/GsonTest.kt
  domain/src/main/java/com/swm/domain/model/Screen.kt
  domain/src/main/java/com/swm/domain/model/ViewType.kt
Labels: feature

#9 Refactor #4 - Adapter에서도 enum 사용하기
  presentation/src/main/java/com/swm/presentation/HomeContentAdapter.kt
Labels: refactor

#12 [FEATURE] - #10 DTO, UseCase 없이 바로 VO로 + #11 RichText 데이터 받아오기
  data/src/main/java/com/swm/data/network/di/DataModule.kt
  data/src/main/java/com/swm/data/network/di/NetworkModule.kt
  data/src/main/java/com/swm/data/network/dto/ScreenDTO.kt
  data/src/main/java/com/swm/data/network/dto/ViewTypeDto.kt
  data/src/main/java/com/swm/data/network/repository/RichTextScreenRepositoryImpl.kt
  data/src/main/java/com/swm/data/network/source/RichTextScreenDataSource.kt
  data/src/main/java/com/swm/data/network/source/ScreenDataSource.kt
  data/src/test/java/com/swm/data/GsonTest.kt
  domain/src/main/java/com/swm/domain/ViewType.kt
  domain/src/main/java/com/swm/domain/model/RichTextVO.kt
  domain/src/main/java/com/swm/domain/model/Screen.kt
  domain/src/main/java/com/swm/domain/model/ViewType.kt
  domain/src/main/java/com/swm/domain/repository/RichTextScreenRepository.kt
  domain/src/main/java/com/swm/domain/usecase/GetScreenUseCase.kt
  presentation/src/main/java/com/swm/presentation/MainActivity.kt
  presentation/src/main/java/com/swm/presentation/MainViewModel.kt
Labels: feature

#15 [Feature] Domain 까지 내려온 RichTextEntity를 Presentation 에서 보여주기
  presentation/src/main/java/com/swm/presentation/BindingAdapter.kt
  presentation/src/main/java/com/swm/presentation/HomeContentAdapter.kt
  presentation/src/main/java/com/swm/presentation/MainActivity.kt
  presentation/src/main/java/com/swm/presentation/MainViewModel.kt
  presentation/src/main/java/com/swm/presentation/adapter/HomeContentAdapter.kt
  presentation/src/main/java/com/swm/presentation/adapter/HomeTitleBadgeAdapter.kt
  presentation/src/main/java/com/swm/presentation/adapter/HomeTypeViewAdapter.kt
  presentation/src/main/java/com/swm/presentation/viewholder/SectionViewHolder.kt
  presentation/src/main/java/com/swm/presentation/viewholder/TypeViewViewHolder.kt
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/view_a_type.xml
  presentation/src/main/res/layout/view_b_type.xml
  presentation/src/main/res/layout/view_plus_title_section.xml
  presentation/src/main/res/layout/view_rich_view_type.xml
Labels: feature

#18 hotfix #17 : 알맞은 Json값으로 떨어지는 것을 파싱하도록 변경
  data/src/main/java/com/swm/data/network/di/NetworkModule.kt
  domain/src/main/java/com/swm/domain/model/RichTextVO.kt
  presentation/src/main/java/com/swm/presentation/BindingAdapter.kt
Labels: bug
